# Generated by Django 6.0.6 on 2026-06-21 03:26

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RoadNode",
            fields=[
                ("osm_id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                "db_table": "road_nodes",
            },
        ),
        migrations.CreateModel(
            name="RoadEdge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("osm_way_id", models.BigIntegerField()),
                ("segment_index", models.PositiveIntegerField()),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.LineStringField(srid=4326),
                ),
                ("length_meters", models.FloatField()),
                ("cost_seconds", models.FloatField()),
                (
                    "source",
                    models.ForeignKey(
                        db_column="source_node_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="routing.roadnode",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        db_column="target_node_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="routing.roadnode",
                    ),
                ),
            ],
            options={
                "db_table": "road_edges",
                "indexes": [
                    models.Index(fields=["osm_way_id"], name="road_edges_way_idx")
                ],
            },
        ),
    ]
