# Generated by Django 6.0.6 on 2026-06-21 03:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="roadedge",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="roadedge",
            name="road_class",
            field=models.CharField(default="unknown", max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="roadedge",
            name="tags",
            field=models.JSONField(default=dict),
        ),
    ]
