# Generated by Django 6.0.6 on 2026-06-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routing", "0002_roadedge_name_roadedge_road_class_roadedge_tags"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="roadedge",
            index=models.Index(
                fields=["osm_way_id", "segment_index", "source", "target"],
                name="road_edges_reverse_idx",
            ),
        ),
    ]
