# Generated by Django 6.0.6 on 2026-06-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routing", "0003_roadedge_road_edges_reverse_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="TurnRestriction",
            fields=[
                (
                    "osm_relation_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("restriction", models.CharField(max_length=64)),
                ("from_way_id", models.BigIntegerField()),
                ("via_node_id", models.BigIntegerField()),
                ("to_way_id", models.BigIntegerField()),
                ("tags", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "turn_restrictions",
                "indexes": [
                    models.Index(
                        fields=["from_way_id", "via_node_id", "to_way_id"],
                        name="turn_restriction_lookup_idx",
                    )
                ],
            },
        ),
    ]
